### ISSUE TITLE
macOS Big Sur 11.3.1 - Cannot open plugin - Notarization problem?

### ISSUE THREAD

**Issue by silviu-bucsa** [sergeishere/Sketch-UI-Inspector#1]
Hello,

Recently found this plugin and wanted to test it out, maybe I learn something new.

Downloaded, installed but I encounter this error:
“Sketch_UI_Inspector.framework” cannot be opened because the developer cannot be verified.
macOS cannot verify that this app is free from malware.
with the options "Move to Bin" and "Cancel"

Using macOS Big Sur 11.3.1 + Sketch Version 72 (124316)

I presume this error pops out because the plugin is not notarized?

Thank you

**Comment by sergeishere** [comment]
Hey @silviu-bucsa !

Unfortunately I have no plans to support this plugin anymore.

There is a source code in this repository so you can clone and rebuild it (then replace the compiled one in the plugin bundle) to avoid this warning message.

**Comment by sergeishere** [comment]
... and you are right - the plugin is not notarized.

**Comment by silviu-bucsa** [comment]
Hey @sergeishere

Thanks for pointing me in the right direction.

Also, btw, Handy Menu Sketch Plugin is pure awesomeness! Please continue to support Handy Menu, it's a real time saver!
